"""Tool metadata for the web playground.

Contains company info, logos, links, and branding for each connector.
Used by the connector detail page for professional presentation.
"""

from __future__ import annotations

# Logo URLs from official sources / CDNs
# Using simple-icons SVG CDN for consistent, high-quality logos
_SI = "https://cdn.simpleicons.org"

TOOL_META: dict[str, dict] = {
    "gmail": {
        "company": "Google",
        "website": "https://mail.google.com",
        "docs": "https://developers.google.com/workspace/gmail/api/reference/rest",
        "github": "",
        "logo": f"{_SI}/gmail",
        "color": "#EA4335",
        "tagline": "Read, send, and manage emails programmatically",
        "auth_methods": ["OAuth 2.0", "Service Account"],
        "pricing": "Free (Google Workspace required for some features)",
        "rate_limit": "250 requests/second per user",
    },
    "gdrive": {
        "company": "Google",
        "website": "https://drive.google.com",
        "docs": "https://developers.google.com/drive/api/reference/rest/v3",
        "github": "",
        "logo": f"{_SI}/googledrive",
        "color": "#4285F4",
        "tagline": "Store, share, and collaborate on files",
        "auth_methods": ["OAuth 2.0", "Service Account"],
        "pricing": "Free (15GB), Google Workspace plans for more",
        "rate_limit": "12,000 requests/minute per project",
    },
    "gcalendar": {
        "company": "Google",
        "website": "https://calendar.google.com",
        "docs": "https://developers.google.com/calendar/api/v3/reference",
        "github": "",
        "logo": f"{_SI}/googlecalendar",
        "color": "#4285F4",
        "tagline": "Schedule events, manage calendars, check availability",
        "auth_methods": ["OAuth 2.0", "Service Account"],
        "pricing": "Free with Google account",
        "rate_limit": "500 requests/100 seconds per user",
    },
    "gsheets": {
        "company": "Google",
        "website": "https://sheets.google.com",
        "docs": "https://developers.google.com/sheets/api/reference/rest",
        "github": "",
        "logo": f"{_SI}/googlesheets",
        "color": "#34A853",
        "tagline": "Read, write, and format spreadsheet data",
        "auth_methods": ["OAuth 2.0", "Service Account"],
        "pricing": "Free with Google account",
        "rate_limit": "300 requests/minute per project",
    },
    "gdocs": {
        "company": "Google",
        "website": "https://docs.google.com",
        "docs": "https://developers.google.com/docs/api/reference/rest",
        "github": "",
        "logo": f"{_SI}/googledocs",
        "color": "#4285F4",
        "tagline": "Create and edit documents programmatically",
        "auth_methods": ["OAuth 2.0", "Service Account"],
        "pricing": "Free with Google account",
        "rate_limit": "300 requests/minute per project",
    },
    "gtasks": {
        "company": "Google",
        "website": "https://tasks.google.com",
        "docs": "https://developers.google.com/tasks/reference/rest",
        "github": "",
        "logo": f"{_SI}/googletasks/4285F4",
        "color": "#4285F4",
        "tagline": "Manage task lists and to-do items",
        "auth_methods": ["OAuth 2.0"],
        "pricing": "Free with Google account",
        "rate_limit": "300 requests/minute per project",
    },
    "slack": {
        "company": "Salesforce (Slack Technologies)",
        "website": "https://slack.com",
        "docs": "https://api.slack.com/methods",
        "github": "https://github.com/slackapi",
        "logo": f"{_SI}/slack",
        "color": "#4A154B",
        "tagline": "Team messaging, channels, and collaboration",
        "auth_methods": ["OAuth 2.0", "Bot Token"],
        "pricing": "Free tier available, Pro from $8.75/user/month",
        "rate_limit": "1 request/second (Tier 2)",
    },
    "discord": {
        "company": "Discord Inc.",
        "website": "https://discord.com",
        "docs": "https://discord.com/developers/docs",
        "github": "https://github.com/discord",
        "logo": f"{_SI}/discord",
        "color": "#5865F2",
        "tagline": "Messaging, voice, and community management",
        "auth_methods": ["Bot Token", "OAuth 2.0"],
        "pricing": "Free, Nitro from $9.99/month",
        "rate_limit": "50 requests/second global",
    },
    "github": {
        "company": "Microsoft (GitHub Inc.)",
        "website": "https://github.com",
        "docs": "https://docs.github.com/en/rest",
        "github": "https://github.com/github",
        "logo": f"{_SI}/github",
        "color": "#181717",
        "tagline": "Code hosting, issues, PRs, and CI/CD",
        "auth_methods": ["Personal Access Token", "OAuth 2.0", "GitHub App"],
        "pricing": "Free for public repos, Teams from $4/user/month",
        "rate_limit": "5,000 requests/hour authenticated",
    },
    "gitlab": {
        "company": "GitLab Inc.",
        "website": "https://gitlab.com",
        "docs": "https://docs.gitlab.com/api/rest/",
        "github": "https://github.com/gitlabhq/gitlabhq",
        "logo": f"{_SI}/gitlab",
        "color": "#FC6D26",
        "tagline": "DevOps platform with Git, CI/CD, and issue tracking",
        "auth_methods": ["Personal Access Token", "OAuth 2.0"],
        "pricing": "Free tier, Premium from $29/user/month",
        "rate_limit": "2,000 requests/minute authenticated",
    },
    "notion": {
        "company": "Notion Labs Inc.",
        "website": "https://notion.so",
        "docs": "https://developers.notion.com/reference",
        "github": "",
        "logo": f"{_SI}/notion",
        "color": "#000000",
        "tagline": "All-in-one workspace for notes, docs, and databases",
        "auth_methods": ["Bearer Token (Integration)", "OAuth 2.0"],
        "pricing": "Free for personal, Plus from $10/user/month",
        "rate_limit": "3 requests/second average",
    },
    "jira": {
        "company": "Atlassian",
        "website": "https://www.atlassian.com/software/jira",
        "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/",
        "github": "",
        "logo": f"{_SI}/jira",
        "color": "#0052CC",
        "tagline": "Project tracking, issue management, and agile boards",
        "auth_methods": ["Basic Auth (email:api_token)", "OAuth 2.0"],
        "pricing": "Free up to 10 users, Standard from $8.15/user/month",
        "rate_limit": "100 requests/minute",
    },
    "stripe": {
        "company": "Stripe Inc.",
        "website": "https://stripe.com",
        "docs": "https://docs.stripe.com/api",
        "github": "https://github.com/stripe",
        "logo": f"{_SI}/stripe",
        "color": "#635BFF",
        "tagline": "Payment processing, subscriptions, and billing",
        "auth_methods": ["API Key (Secret Key)"],
        "pricing": "2.9% + 30c per transaction",
        "rate_limit": "100 read/sec, 100 write/sec",
    },
    "openai": {
        "company": "OpenAI",
        "website": "https://openai.com",
        "docs": "https://platform.openai.com/docs/api-reference",
        "github": "https://github.com/openai",
        "logo": f"{_SI}/openai",
        "color": "#412991",
        "tagline": "GPT models, embeddings, and AI capabilities",
        "auth_methods": ["API Key"],
        "pricing": "Pay-per-token (varies by model)",
        "rate_limit": "Varies by model and tier",
    },
    "anthropic": {
        "company": "Anthropic",
        "website": "https://anthropic.com",
        "docs": "https://docs.anthropic.com/en/api",
        "github": "https://github.com/anthropics",
        "logo": f"{_SI}/anthropic",
        "color": "#191919",
        "tagline": "Claude models for safe, capable AI",
        "auth_methods": ["API Key"],
        "pricing": "Pay-per-token (varies by model)",
        "rate_limit": "Varies by model and tier",
    },
    "salesforce": {
        "company": "Salesforce Inc.",
        "website": "https://salesforce.com",
        "docs": "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/",
        "github": "https://github.com/salesforce",
        "logo": f"{_SI}/salesforce",
        "color": "#00A1E0",
        "tagline": "CRM, sales, service, and marketing platform",
        "auth_methods": ["OAuth 2.0", "Bearer Token"],
        "pricing": "Enterprise pricing (from $25/user/month)",
        "rate_limit": "Varies by edition",
    },
    "hubspot": {
        "company": "HubSpot Inc.",
        "website": "https://hubspot.com",
        "docs": "https://developers.hubspot.com/docs/api/crm",
        "github": "https://github.com/HubSpot",
        "logo": f"{_SI}/hubspot",
        "color": "#FF7A59",
        "tagline": "CRM, marketing, sales, and service hub",
        "auth_methods": ["Bearer Token (Private App)", "OAuth 2.0"],
        "pricing": "Free CRM, Starter from $20/month",
        "rate_limit": "100 requests/10 seconds (private apps)",
    },
}

# Default metadata for connectors not in the registry
_DEFAULT_META: dict[str, str] = {
    "company": "",
    "website": "",
    "docs": "",
    "github": "",
    "logo": "",
    "color": "#6366f1",
    "tagline": "",
    "auth_methods": [],
    "pricing": "",
    "rate_limit": "",
}


def get_tool_meta(name: str) -> dict:
    """Get metadata for a connector, with defaults for unknown tools."""
    meta = dict(_DEFAULT_META)
    if name in TOOL_META:
        meta.update(TOOL_META[name])
    return meta
